### ISSUE TITLE
GCloud email and private key documentation

### ISSUE THREAD

**Issue by greyhenna** [JoaoDanielRufino/sarve-bot#18]
Hi could you help by adding documentation for getting gcloud mail and private key.
Im struck here,

2022-01-09T07:07:32.413629+00:00 app[worker.1]: Error: 16 UNAUTHENTICATED: Failed to retrieve auth metadata with error: error:0909006C:PEM routines:get_name:no start line
2022-01-09T07:07:32.413629+00:00 app[worker.1]:     at Object.callErrorFromStatus (/app/node_modules/@grpc/grpc-js/build/src/call.js:31:26)
2022-01-09T07:07:32.413630+00:00 app[worker.1]:     at Object.onReceiveStatus (/app/node_modules/@grpc/grpc-js/build/src/client.js:391:49)
2022-01-09T07:07:32.413630+00:00 app[worker.1]:     at Object.onReceiveStatus (/app/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:328:181)
2022-01-09T07:07:32.413630+00:00 app[worker.1]:     at /app/node_modules/@grpc/grpc-js/build/src/call-stream.js:182:78
2022-01-09T07:07:32.413631+00:00 app[worker.1]:     at processTicksAndRejections (node:internal/process/task_queues:78:11) {
2022-01-09T07:07:32.413631+00:00 app[worker.1]:   code: 16,
2022-01-09T07:07:32.413631+00:00 app[worker.1]:   details: 'Failed to retrieve auth metadata with error: error:0909006C:PEM routines:get_name:no start line',
2022-01-09T07:07:32.413631+00:00 app[worker.1]:   metadata: Metadata { internalRepr: Map(0) {}, options: {} }
2022-01-09T07:07:32.413631+00:00 app[worker.1]: }

**Comment by JoaoDanielRufino** [comment]
Hello @greyhenna , you need to create a gcloud project and get the credentials. After that, you need to enable the `speech-to-text` api from gcloud as well.

Please, see this [link](https://cloud.google.com/docs/authentication/getting-started) to get the credentials and this [link](https://cloud.google.com/speech-to-text/docs/quickstart-gcloud) to enable `speech-to-text`.

**Comment by greyhenna** [comment]
> Hello @greyhenna , you need to create a gcloud project and get the credentials. After that, you need to enable the `speech-to-text` api from gcloud as well.
> 
> Please, see this [link](https://cloud.google.com/docs/authentication/getting-started) to get the credentials and this [link](https://cloud.google.com/speech-to-text/docs/quickstart-gcloud) to enable `speech-to-text`.

Thanks @JoaoDanielRufino  . It helped.
